export const Product = [
  {
    id: 1,
    name: "Nike Air Force 1 '07",
    category: "Men",
    price: 11495,
    qty: 1,
    stock: 50,
    imageUrl:
      "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,b_rgb:f5f5f5/7ef38ab5-528e-4da4-b27d-0603e6923f76/air-force-1-07-shoes-dTN9bg.png",
  },
  {
    id: 2,
    name: "LITTLE KID & BIG KID LITE RACER ADAPT 5.0 SUSTAINABLE RUNNING SHOES",
    category: "Kids",
    qty: 1,
    stock: 50,
    price: 7524,
    imageUrl: require("../../Assets/BOYS' ADIDAS LITTLE KID & BIG KID LITE RACER ADAPT 5.0 SUSTAINABLE RUNNING SHOES.avif"),
  },

  {
    id: 3,
    name: "KIDS' VANS DOHENY SKATE SHOES",
    category: "Kids",
    qty: 1,
    stock: 50,
    price: 4233,
    imageUrl: require("../../Assets/KIDS' VANS LITTLE KID & BIG KID DOHENY SKATE SHOES.avif"),
  },
  {
    id: 4,
    name: "ADIDAS DAILY 3.0 SNEAKERS ",
    category: "Men",
    qty: 1,
    stock: 50,
    price: 1123,
    imageUrl: require("../../Assets/MEN'S ADIDAS DAILY 3.0 SNEAKERS.avif"),
  },

  {
    id: 5,
    name: "ADIDAS HOOPS 3.0 MID SNEAKERS",
    category: "Men",
    qty: 1,
    stock: 50,
    price: 8709,
    imageUrl: require("../../Assets/MEN'S ADIDAS HOOPS 3.0 MID SNEAKERS.avif"),
  },
  {
    id: 6,
    name: "NEW BALANCE MT481 TRAIL RUNNING SHOES",
    category: "Men",
    qty: 1,
    stock: 50,
    price: 2344,
    imageUrl: require("../../Assets/MEN'S NEW BALANCE MT481 TRAIL RUNNING SHOES.avif"),
  },
  {
    id: 7,
    name: "MEN'S ADIDAS QUESTAR SNEAKERS",
    category: "Men",
    qty: 1,
    stock: 50,
    price: 1123,
    imageUrl: require("../../Assets/MEN'S ADIDAS QUESTAR SNEAKERS.avif"),
  },
  {
    id: 8,
    name: "NEW BALANCE MT481 WEATHERIZED TRAIL RUNNING SHOES",
    category: "Men",
    qty: 1,
    stock: 50,
    price: 11323,
    imageUrl: require("../../Assets/MEN'S NEW BALANCE MT481 WEATHERIZED TRAIL RUNNING SHOES.avif"),
  },
  {
    id: 9,
    name: "VANS WARD SKATE SHOES",
    category: "Men",
    qty: 1,
    stock: 50,
    price: 11123,
    imageUrl: require("../../Assets/MEN'S VANS WARD SKATE SHOES.avif"),
  },
  {
    id: 10,
    C: "NIKE AIR MAX EXCEE SNEAKERS",
    category: "Men",
    qty: 1,
    stock: 50,
    price: 18123,
    imageUrl: require("../../Assets/NIKE AIR MAX EXCEE SNEAKERS.avif"),
  },
  {
    id: 11,
    name: "KID POST MOVE MID SNEAKERS.avif",
    category: "Kids",
    qty: 1,
    stock: 50,
    price: 16123,
    imageUrl: require("../../Assets/BOYS' ADIDAS LITTLE KID & BIG KID POST MOVE MID SNEAKERS.avif"),
  },
  {
    id: 12,
    name: "WOMEN'S MAKALU MARTY BOOTIES 2.avif",
    category: "Women",
    qty: 1,
    stock: 50,
    price: 16123,
    imageUrl: require("../../Assets/WOMEN'S MAKALU MARTY BOOTIES 2.avif"),
  },
  {
    id: 13,
    name: "WOMEN'S MAKALU MARTY BOOTIES.avif",
    category: "Women",
    qty: 1,
    stock: 50,
    price: 16123,
    imageUrl: require("../../Assets/WOMEN'S MAKALU MARTY BOOTIES.avif"),
  },
  {
    id: 14,
    name: "WOMEN'S NEW BALANCE ROAV V1 SNEAKERS.avif",
    category: "Women",
    qty: 1,
    stock: 50,
    price: 16123,
    imageUrl: require("../../Assets/WOMEN'S NEW BALANCE ROAV V1 SNEAKERS.avif"),
  },
  {
    id: 15,
    name: "WOMEN'S SOLANZ CHERLIE RUCHED BOOTIES.avif",
    category: "Women",
    qty: 1,
    stock: 50,
    price: 16123,
    imageUrl: require("../../Assets/WOMEN'S SOLANZ CHERLIE RUCHED BOOTIES.avif"),
  },
];
